### PR TITLE
README.md: Add contributing/running tests section

### PR DESCRIPTION
**Pull request by msabramo**
with links to:

- [test/README.md](test/README.md)
- [test/functional/README.md](test/functional/README.md)

because I was looking for info on how to run tests in the main `README.md` and didn't find it and I only found about these other docs when @willdurand kindly pointed them out to me in https://github.com/hipache/hipache/issues/194#issuecomment-68644456

### CODE REVIEW

**Comment by willdurand** [comment]
Weird that the test suite fails for such a change..

:+1: otherwise

**Comment by msabramo** [comment]
Yeah, test failure looks spurious and unrelated to my change. 

Can an admin please tell Travis to retest?

**Comment by dmp42** [comment]
Restarted. You should be able to trigger a rebuild by just `git push -f` it.

**Comment by dmp42** [comment]
LGTM otherwise! Nice to see interest in these.

**Comment by dmp42** [comment]
What about a `CONTRIBUTING.md` document where these (and other dev infos) would be put, instead of into the general README doc?

**Comment by willdurand** [comment]
Agreed on a `CONTRIBUTING` file. Any template that you would like to use? I use [this](https://github.com/willdurand/Hateoas/blob/master/CONTRIBUTING.md) in most of my projects, and it should be easy to adapt it for this projet.

**Comment by msabramo** [comment]
OK, I moved the testing info from `README.md` to `CONTRIBUTING.md` (and put a link in `README.md` to `CONTRIBUTING.md`.

I'll leave it to someone more experienced to:

- Document the canonical way to run the tests - I'm getting a lot of failures, so I'm not sure I'm doing stuff right.
- Document what the standards are for coding, commit messages, etc.

**Comment by willdurand** [comment]
To me, it is really important to add:

>Here are a few rules to follow in order to ease code reviews, and discussions before maintainers accept and merge your work.
>
>You MUST run the test suite.
>
>You MUST write (or update) unit tests.
>
>You SHOULD write documentation.
>
>Please, write commit messages that make sense, and rebase your branch before submitting your Pull Request.
>
>One may ask you to squash your commits too. This is used to "clean" your Pull Request before merging it (we don't want commits such as fix tests, fix 2, fix 3, etc.).
>
>Also, while creating your Pull Request on GitHub, you MUST write a description which gives the context and/or explains why you are creating it.
>
>Thank you!

**Comment by dmp42** [comment]
+1 on @willdurand suggestion

**Comment by msabramo** [comment]
Implemented @willdurand's suggestion.

See: https://github.com/msabramo/hipache/blob/patch-4/CONTRIBUTING.md

**Comment by Starefossen** [comment]
LGTM

**Comment by dmp42** [comment]
Merged then :)

**Comment by willdurand** [comment]
youpi!

**Pull request merged**
